import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Header } from "@/components/global/Header";
import { NavbarInformation } from "@/components/global/NavbarInformation";
import { SSRProvider } from "@react-aria/ssr";
import { Footer } from "@/components/global/Footer";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Mercado Libre Argentina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SSRProvider>
        <Header />
        <NavbarInformation />
        <Component {...pageProps} />
        <Footer />
      </SSRProvider>
    </>
  );
}
